# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-13 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('sch_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('img_url', models.TextField()),
                ('type', models.CharField(choices=[(0, 'Salesman'), (1, 'Customer')], max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Salesman',
        ),
        migrations.AddField(
            model_name='schedule',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='Demo.User'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='salesman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesman', to='Demo.User'),
        ),
    ]
