# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-13 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demo', '0002_auto_20170513_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.BooleanField(choices=[(True, 'Salesman'), (False, 'Customer')]),
        ),
    ]
