# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-13 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demo', '0003_auto_20170513_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='type',
        ),
        migrations.AddField(
            model_name='user',
            name='is_salesman',
            field=models.BooleanField(choices=[(True, 'yes'), (False, 'no')], default=True),
            preserve_default=False,
        ),
    ]
